apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ha-postgres-cluster
  namespace: production
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi
    storageClass: longhorn

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: postgresql.cnpg.io/cluster
                operator: In
                values:
                  - ha-postgres-cluster
          topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  monitoring:
    enablePodMonitor: true
