#!/usr/bin/env python3
"""
Talos Kubernetes Platform - Target Configuration & Verification Wizard
Guides the developer through setting, verifying, and persisting the deployment target.
Generates target.env and terraform.tfvars files upon successful connectivity validation.
"""

import argparse
import os
import re
import subprocess
import sys

GREEN = "\033[32m"
RED = "\033[31m"
YELLOW = "\033[33m"
BLUE = "\033[36m"
BOLD = "\033[1m"
RESET = "\033[0m"

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

def parse_ssh_config(host_alias="t5600"):
    """Extract host configuration from ~/.ssh/config if available."""
    ssh_config_path = os.path.expanduser("~/.ssh/config")
    defaults = {
        "host": "192.168.9.110",
        "user": os.getenv("USER", "bjarrett"),
        "key": os.path.expanduser("~/.ssh/id_ed25519")
    }

    if not os.path.exists(ssh_config_path):
        return defaults

    try:
        with open(ssh_config_path, "r") as f:
            content = f.read()

        match = re.search(r"Host\s+" + re.escape(host_alias) + r"\b([\s\S]*?)(?=Host\s+|\Z)", content, re.IGNORECASE)
        if match:
            block = match.group(1)
            hn = re.search(r"HostName\s+(\S+)", block, re.IGNORECASE)
            usr = re.search(r"User\s+(\S+)", block, re.IGNORECASE)
            idf = re.search(r"IdentityFile\s+(\S+)", block, re.IGNORECASE)

            if hn:
                defaults["host"] = hn.group(1)
            if usr:
                defaults["user"] = usr.group(1)
            if idf:
                defaults["key"] = os.path.expanduser(idf.group(1))
    except Exception:
        pass

    return defaults

def prompt_value(prompt_text, default_val):
    """Prompt user for input with a default value."""
    if not sys.stdin.isatty():
        return default_val
    try:
        val = input(f"{BOLD}{prompt_text}{RESET} [{default_val}]: ").strip()
        return val if val else default_val
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(1)

def verify_target(host, user, key_path, pool_name, net_name):
    """Perform live validation against the target server."""
    print(f"\n{BLUE}===> Verifying connectivity & hypervisor prerequisites on {host}...{RESET}")

    ssh_opts = ["ssh", "-o", "ConnectTimeout=4", "-o", "StrictHostKeyChecking=no", "-i", key_path, f"{user}@{host}"]

    # 1. SSH Handshake
    res = subprocess.run(ssh_opts + ["hostname"], capture_output=True, text=True)
    if res.returncode != 0:
        print(f"  {RED}✗ SSH Connection Failed:{RESET} {res.stderr.strip()}")
        return False, None
    remote_hostname = res.stdout.strip()
    print(f"  {GREEN}✓ SSH Handshake Succeeded{RESET} (Remote Host: {BOLD}{remote_hostname}{RESET})")

    # 2. Hardware KVM Passthrough
    res = subprocess.run(ssh_opts + ["[ -e /dev/kvm ] && echo OK || echo MISSING"], capture_output=True, text=True)
    if "OK" not in res.stdout:
        print(f"  {RED}✗ Hardware KVM missing on target server (/dev/kvm not found){RESET}")
        return False, None
    print(f"  {GREEN}✓ Hardware KVM passthrough active{RESET} (/dev/kvm present)")

    # 3. Remote Libvirtd Daemon Responsiveness
    res = subprocess.run(ssh_opts + ["virsh -c qemu:///system list --all >/dev/null 2>&1 && echo OK || echo FAIL"], capture_output=True, text=True)
    if "OK" not in res.stdout:
        print(f"  {RED}✗ Libvirtd daemon unresponsive on target server (qemu:///system){RESET}")
        return False, None
    print(f"  {GREEN}✓ Libvirtd system daemon responsive{RESET}")

    # 4. Storage Pool Verification
    res = subprocess.run(ssh_opts + ["virsh -c qemu:///system pool-list --all"], capture_output=True, text=True)
    if pool_name not in res.stdout:
        print(f"  {YELLOW}⚠ Storage pool '{pool_name}' not listed as active in libvirt{RESET}")
    else:
        print(f"  {GREEN}✓ Storage pool '{pool_name}' active{RESET}")

    # 5. Network Bridge Verification
    res = subprocess.run(ssh_opts + ["virsh -c qemu:///system net-list --all"], capture_output=True, text=True)
    if net_name not in res.stdout:
        print(f"  {YELLOW}⚠ Network bridge '{net_name}' not listed as active in libvirt{RESET}")
    else:
        print(f"  {GREEN}✓ Network bridge '{net_name}' active{RESET}")

    return True, remote_hostname

def write_configs(host, user, key_path, pubkey_path, pool_name, net_name, mac_addr):
    """Write target.env and terraform.tfvars files."""
    libvirt_uri = f"qemu+ssh://{user}@{host}/system?keyfile={key_path}"

    # 1. target.env
    target_env_path = os.path.join(REPO_ROOT, "target.env")
    with open(target_env_path, "w") as f:
        f.write(f"""# Generated by 'make configure'
TARGET_HOST="{host}"
TARGET_USER="{user}"
TARGET_SSH_KEY="{key_path}"
TARGET_SSH_PUBKEY="{pubkey_path}"
TARGET_LIBVIRT_URI="{libvirt_uri}"
TARGET_STORAGE_POOL="{pool_name}"
TARGET_NETWORK="{net_name}"
TARGET_MAC="{mac_addr}"
""")
    print(f"  {GREEN}✓ Generated:{RESET} target.env")

    # 2. Stage 1 terraform.tfvars
    stage1_tfvars_path = os.path.join(REPO_ROOT, "terraform", "environments", "01-nested-sandbox", "terraform.tfvars")
    with open(stage1_tfvars_path, "w") as f:
        f.write(f"""# Generated by 'make configure'
libvirt_uri     = "{libvirt_uri}"
storage_pool    = "{pool_name}"
network_name    = "{net_name}"
mac_address     = "{mac_addr}"
""")
    print(f"  {GREEN}✓ Generated:{RESET} terraform/environments/01-nested-sandbox/terraform.tfvars")

    # 3. Stage 2 terraform.tfvars
    stage2_tfvars_path = os.path.join(REPO_ROOT, "terraform", "environments", "02-talos-cluster", "terraform.tfvars")
    with open(stage2_tfvars_path, "w") as f:
        f.write(f"""# Generated by 'make configure'
libvirt_uri  = "{libvirt_uri}"
storage_pool = "{pool_name}"
network_name = "{net_name}"
""")
    print(f"  {GREEN}✓ Generated:{RESET} terraform/environments/02-talos-cluster/terraform.tfvars")

def main():
    parser = argparse.ArgumentParser(description="Target Server Configuration & Verification Wizard")
    parser.add_argument("--non-interactive", action="store_true", help="Run without prompts using defaults/arguments")
    parser.add_argument("--host", help="Target server IP or hostname")
    parser.add_argument("--user", help="SSH username on target server")
    parser.add_argument("--key", help="Path to SSH private key")
    parser.add_argument("--pool", default="default", help="Libvirt storage pool name (default: default)")
    parser.add_argument("--network", default="default", help="Libvirt network name (default: default)")
    parser.add_argument("--mac", default="52:54:00:BA:67:8E", help="Static MAC reservation for sandbox VM")
    args = parser.parse_args()

    print(f"\n{BLUE}{BOLD}=============================================================================={RESET}")
    print(f"{BLUE}{BOLD}     Talos Kubernetes Platform - Deployment Target Setup Wizard               {RESET}")
    print(f"{BLUE}{BOLD}=============================================================================={RESET}\n")

    detected = parse_ssh_config("t5600")

    host = args.host or (detected["host"] if args.non_interactive else prompt_value("Target Server Hostname or IP", detected["host"]))
    user = args.user or (detected["user"] if args.non_interactive else prompt_value("SSH Username", detected["user"]))
    
    default_key = detected["key"]
    if not os.path.exists(default_key):
        rsa_candidate = os.path.expanduser("~/.ssh/id_rsa")
        if os.path.exists(rsa_candidate):
            default_key = rsa_candidate

    key_path = os.path.abspath(os.path.expanduser(args.key or (default_key if args.non_interactive else prompt_value("SSH Private Key Path", default_key))))
    pubkey_path = key_path + ".pub" if os.path.exists(key_path + ".pub") else key_path

    pool_name = args.pool if args.non_interactive else prompt_value("Libvirt Storage Pool", args.pool)
    net_name = args.network if args.non_interactive else prompt_value("Libvirt Network Bridge", args.network)
    mac_addr = args.mac if args.non_interactive else prompt_value("Sandbox VM MAC Address", args.mac)

    if not os.path.exists(key_path):
        print(f"\n{RED}Error: Private key file not found at '{key_path}'.{RESET}")
        return 1

    ok, remote_host = verify_target(host, user, key_path, pool_name, net_name)
    if not ok:
        print(f"\n{RED}{BOLD}Target verification failed. Please correct credentials or connectivity and retry.{RESET}\n")
        return 1

    print(f"\n{BLUE}===> Persisting verified target configuration...{RESET}")
    write_configs(host, user, key_path, pubkey_path, pool_name, net_name, mac_addr)

    print(f"\n{GREEN}{BOLD}🎉 Target deployment server '{remote_host}' ({host}) configured & verified!{RESET}")
    print(f"{GREEN}You can now run 'make preflight' or proceed to infrastructure provisioning.{RESET}\n")
    return 0

if __name__ == "__main__":
    sys.exit(main())
